apiVersion: v1
kind: Service
metadata:
  name: loadbalancer
  namespace: webportal
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: 'true'
spec:
  selector:
    app: webportal
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000